---
title: "CINmetrics analysis"
author: "Sasha Thalluri"
date: "8/23/2021"
output: html_document
---

This R Markdown will have the analysis to compare the CINmetrics to one another across the 33 cancers in TCGA. The output of this document will include corr plots, heatmaps, ridgeline plots, and strip chart.

```{r}
### Title: Master File for CIN Metrics Visualizations
### Written by: Roshan Darji
### Date: 2018.09.28
### Goal: Create visualizations for CIN metrics
### Adapted from masterCIN.R

##### Packages #####
library(tidyverse)
suppressPackageStartupMessages(library(data.table))

##### Initial data #####
load("cin-metrics/data/master/190318_cin-metrics-master_calcs_tcga.df.RData")
load("cin-metrics/data/master/190318_cin-metrics-master_stats.RData")

##### Ridgeline Plots #####
pdf(file = "cin-metrics/graphs/190318_cin-metrics-master_graphs_ridgeline.pdf",
    width = 13, height = 8)
### numBases
tcga.df$Project <- factor(tcga.df$Project, levels = levels(gdata::reorder.factor(tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                                 tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$numBases.3,
                                                                                 median)))
ggplot(tcga.df,
       aes(x = numBases.3,
           #y = reorder(tcga.df$Project, tcga.df$numBases.3, FUN = median),
           y = Project,
           fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.02, scale = 1.5, alpha = 0.8) +
  #facet_grid(`Sample Type` ~ .) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9, 1e12)) +
  #scale_x_sqrt() +
  coord_cartesian(xlim = c(1e3,1e10)) +
  xlab("\nNumber of Bases") +
  ylab("") +
  #ggtitle(label = "Distributions of the Number of Bases in TCGA Projects") +
  guides(fill = guide_legend(title = NULL, reverse = FALSE))

### numBreakPoints
tcga.df$Project <- factor(tcga.df$Project, levels = levels(gdata::reorder.factor(tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                                 tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$numBreakPoints.3,
                                                                                 median)))
ggplot(tcga.df, aes(x = numBreakPoints.3,
                    #y = reorder(tcga.df$Project, tcga.df$numBreakPoints.3, FUN = median),
                    y = Project,
                    fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.02, scale = 1.5, alpha = 0.8) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  #scale_x_log10() +
  xlab("\nNumber of Break Points") +
  ylab("") +
  #ggtitle(label = "Distributions of the Number of Break Points in TCGA Projects") +
  guides(fill = guide_legend(title = NULL, reverse = TRUE))

### tai
# temporary object to correctly reorder this plot
tmp <- tcga.df[!is.na(tai.3)]
tmp$Project <- factor(tmp$Project, levels = levels(gdata::reorder.factor(tmp[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                         tmp[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$tai.3,
                                                                         median)))
ggplot(tmp, aes(x = tai.3,
                #y = reorder(tcga.df$Project, tcga.df$tai.3, FUN = median),
                y = Project,
                fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.02, scale = 1.5, alpha = 0.8) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  #scale_x_continuous(trans = "log1p", breaks = c(0, 1, 2, 3)) +
  #scale_x_sqrt() +
  coord_cartesian(xlim = c(0,3.5)) +
  xlab("\nTotal Aberration Index Score") +
  ylab("") +
  #ggtitle(label = "Distributions of Total Aberration Index Score in TCGA Projects") +
  guides(fill = guide_legend(title = NULL, reverse = TRUE))
rm(tmp)

### mod.tai
# temporary object to correctly reorder this plot
tmp <- tcga.df[!is.na(mod.tai.3)]
tmp$Project <- factor(tmp$Project, levels = levels(gdata::reorder.factor(tmp[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                         tmp[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$mod.tai.3,
                                                                         median)))
ggplot(tmp, aes(x = mod.tai.3,
                #y = reorder(tcga.df$Project, tcga.df$tai.3, FUN = median),
                y = Project,
                fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.02, scale = 1.5, alpha = 0.8) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  #scale_x_continuous(trans = "log1p", breaks = c(-1e-1, -1e-3, 0 , 1e-3, 1e-1)) +
  scale_x_sqrt() +
  #coord_cartesian(xlim = c(-0.025,0.03)) +
  xlab("\nTotal Aberration Index Score") +
  ylab("") +
  #ggtitle(label = "Distributions of Total Aberration Index Score in TCGA Projects") +
  guides(fill = guide_legend(title = NULL, reverse = TRUE))
rm(tmp)

### fga
tcga.df$Project <- factor(tcga.df$Project, levels = levels(gdata::reorder.factor(tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                                 tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$fga.3,
                                                                                 median)))
ggplot(tcga.df, aes(x = (fga.3 + 1e-12),
                    #y = reorder(tcga.df$Project, tcga.df$fga.3, FUN = median),
                    y = Project,
                    fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.02, scale = 1.5, alpha = 0.8) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  #scale_x_continuous(trans = "log1p", breaks = c(1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1)) +
  #scale_x_sqrt() +
  scale_x_log10(na.value = NULL) +
  coord_cartesian(xlim = c(1e-7,1.2)) +
  xlab("\nFraction of the Genome Altered") +
  ylab("") +
  #ggtitle(label = "Distributions of Fraction Genome Altered in TCGA Projects") +
  guides(fill = guide_legend(title = NULL, reverse = TRUE))

### cna
tcga.df$Project <- factor(tcga.df$Project, levels = levels(gdata::reorder.factor(tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$Project,
                                                                                 tcga.df[`Sample Type` == "Primary Solid Tumor" | `Sample Type` == "Primary Blood Derived Cancer"]$cna.3,
                                                                                 median)))
ggplot(tcga.df, aes(x = cna.3,
                    #y = reorder(tcga.df$Project, tcga.df$cna.3, FUN = median),
                    y = Project,
                    fill = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  ggridges::geom_density_ridges(rel_min_height = 0.04, scale = 1.5, alpha = 0.8) +
  #facet_grid(rows = vars(tcga.df$`Sample Type`)) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000)) +
  coord_cartesian(xlim = c(0,1500)) +
  #scale_x_log10() +
  xlab("\nNumber of Copy Number Aberrations") +
  ylab("") +
  #ggtitle(label = "Distributions of the Number of Copy Number Aberrations") +
  guides(fill = guide_legend(title = NULL, reverse = TRUE))

dev.off()

##### Corrplots #####
pdf(file = "cin-metrics/graphs/190318_cin-metrics-master_graphs_corrplot.pdf",
    width = 13, height = 8)
### Spearman's correlation for ALL samples
corrplot::corrplot(corr = spear,
                   method = "shade", #type = "upper",
                   title = "TCGA Spearman Correlation Matrix", outline = FALSE,
                   order = "hclust", sig.level = 0.05,
                   insig = "blank", mar = c(1,0,3,2))
### Spearman's correlation for Tumor samples
corrplot::corrplot(corr = spear.tumor,
                   method = "shade", #type = "upper",
                   title = "TCGA Spearman Correlation Matrix for Tumor Samples", outline = FALSE,
                   order = "hclust", sig.level = 0.05,
                   insig = "blank", mar = c(1,0,3,2))
### Spearman's Correlation for Normal samples
corrplot::corrplot(corr = spear.normal,
                   method = "shade", #type = "upper",
                   title = "TCGA Spearman Correlation Matrix for Normal Samples", outline = FALSE,
                   order = "hclust", sig.level = 0.05,
                   insig = "blank", mar = c(1,0,3,2))
dev.off()

##### CIN Metric Correlation Heatmap #####
pdf(file = "cin-metrics/graphs/190320_cin-metrics-master_graphs_cin-heatmaps.pdf",
    width = 8, height = 11)
### Renaming column names of spear.tcga, spear.tumor.tcga, and spear.normal.tcga
colnames(spear.tcga) <- c("Bases vs Bases", "Break Points vs Bases", "TAI vs Bases", "Mod TAI vs Bases", "FGA vs Bases", "CNA vs Bases",
                          "Break Points vs Bases", "Break Points vs Break Points", "TAI vs Break Points", "Mod TAI vs Break Points", "FGA vs Break Points", "CNA vs Break Points",
                          "Bases vs TAI", "Break Points vs TAI", "TAI vs TAI", "Mod TAI vs TAI", "FGA vs TAI", "CNA vs TAI",
                          "Bases vs Mod TAI", "Break Points vs Mod TAI", "TAI vs Mod TAI", "Mod TAI vs Mod TAI", "FGA vs Mod TAI", "CNA vs Mod TAI",
                          "Bases vs FGA", "Break Points vs FGA", "TAI vs FGA", "Mod TAI vs FGA", "FGA vs FGA", "CNA vs FGA",
                          "Bases vs CNA", "Break Points vs CNA", "TAI vs CNA", "Mod TAI vs CNA", "FGA vs CNA", "CNA vs CNA")
colnames(spear.tumor.tcga) <- colnames(spear.tcga); colnames(spear.normal.tcga) <- colnames(spear.tcga) 

### All samples
gplots::heatmap.2(as.matrix(na.omit(spear.tcga[, -c(1, 5, 7, 8, 12, 13:15, 19:22, 25:29, 31:36)])),
                  col = viridis::cividis, na.color = "grey", breaks = seq(-1,1, length.out = 31), symbreaks = TRUE,
                  dendrogram = "row", density.info = "density",
                  srtCol = 45,
                  main = "Spearman's Corrleation \nbetween CIN Metrics in TCGA",
                  key.xlab = "Spearman's Rho",
                  key.ylab = NA, key.title = NA, keysize = 1,
                  #cexCol = 1.5, cexRow = 1.3,
                  offsetCol = 1, margins = c(13,5), trace = "none")


### Tumor samples
gplots::heatmap.2(as.matrix(na.omit(spear.tumor.tcga[, -c(1, 5, 7, 8, 12, 13:15, 19:22, 25:29, 31:36)])),
                  col = viridis::cividis, na.color = "grey", breaks = seq(-1,1, length.out = 31), symbreaks = TRUE,
                  dendrogram = "row", density.info = "density",
                  srtCol = 45,
                  main = "Spearman's Corrleation \nbetween CIN Metrics in TCGA Tumor Samples",
                  key.xlab = "Spearman's Rho",
                  key.ylab = NA, key.title = NA, keysize = 1,
                  #cexCol = 1.5, cexRow = 1.3,
                  offsetCol = 1, margins = c(13,5), trace = "none")

### Normal Samples
gplots::heatmap.2(as.matrix(na.omit(spear.normal.tcga[, -c(1, 5, 7, 8, 12, 13:15, 19:22, 25:29, 31:36)])),
                  col = viridis::cividis, na.color = "grey", breaks = seq(-1,1, length.out = 31), symbreaks = TRUE,
                  dendrogram = "row", density.info = "density",
                  srtCol = 45,
                  main = "Spearman's Corrleation \nbetween CIN Metrics in TCGA Normal Samples",
                  key.xlab = "Spearman's Rho",
                  key.ylab = NA, key.title = NA, keysize = 1,
                  #cexCol = 1.5, cexRow = 1.3,
                  offsetCol = 1, margins = c(13,5), trace = "none")
dev.off()

##### numBases Scatter Plots #####
# numBases vs numBreakPoints
ggplot(tcga.df,
       aes(y = numBases.3, x = numBreakPoints.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.7, size = 2) +
  #geom_smooth(method = "lm", se = FALSE, size = 0.5) +
  #theme_minimal() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  coord_cartesian(xlim = c(0, 10000), ylim = c(0,5e9)) +
  labs(y = "Number of Bases",
       x = "Number of Break Points") +
  #ggtitle(label = "Number of Bases vs Number of Break Points") +
  labs(color = NULL) +
  guides(color = FALSE)#guide_legend(override.aes = list(alpha = 1, size = 2)))

# numBases vs. tai
ggplot(tcga.df,
       aes(y = numBases.3, x = tai.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9)) +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Bases")) +
  labs(xlab("Total Aberration Index Score")) +
  ggtitle(label = "Number of Bases vs Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBases vs. mod.tai
ggplot(tcga.df,
       aes(y = numBases.3, x = mod.tai.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9)) +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Bases")) +
  labs(xlab("Modified Total Aberration Index Score")) +
  ggtitle(label = "Number of Bases vs Modified Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBases vs fga
ggplot(tcga.df,
       aes(y = numBases.3, x = fga.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9)) +
  scale_x_log10() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Bases")) +
  labs(xlab("Fraction Genome Altered")) +
  ggtitle(label = "Number of Bases vs Fraction Genome Altered") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBases vs. cna
ggplot(tcga.df,
       aes(y = numBases.3, x = cna.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 1e3, 1e6, 1e9)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Bases")) +
  labs(xlab("Number of Break Points")) +
  ggtitle(label = "Number of Bases vs Number of Copy Number Aberrations") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

##### numBreakPoints Scatter Plots #####
# numBreakPoints vs tai
ggplot(tcga.df,
       aes(y = numBreakPoints.3, x = tai.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Break Points")) +
  labs(xlab("Total Aberration Index Score")) +
  ggtitle(label = "Number of Break Points vs Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBreakPoints vs mod.tai
ggplot(tcga.df,
       aes(y = numBreakPoints.3, x = mod.tai.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  scale_x_log10() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Break Points")) +
  labs(xlab("Modified Total Aberration Index Score")) +
  ggtitle(label = "Number of Break Points vs Modified Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBreakPoints vs fga
ggplot(tcga.df,
       aes(y = numBreakPoints.3, x = fga.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000, 100000)) +
  scale_x_log10() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Break Points")) +
  labs(xlab("Fraction Genome Altered")) +
  ggtitle(label = "Number of Break Points vs Fraction Genome Altered") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# numBreakPoints vs cna
ggplot(tcga.df,
       aes(y = numBreakPoints.3, x = cna.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  scale_x_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(xlab("Number of Copy Number Aberrations")) +
  labs(ylab("Number of Break Points")) +
  ggtitle(label = "Number of Break Points vs Number of Copy Number Aberrations") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

##### tai Scatter Plots #####
# tai vs mod.tai
ggplot(tcga.df,
       aes(x = tai.3, y = mod.tai.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  #scale_x_log10() +
  labs(xlab("Total Aberration Index Score")) +
  labs(ylab("Modified Total Aberration Index Score")) +
  ggtitle(label = "Total Aberration Index vs Modified Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

# tai vs fga
ggplot(tcga.df,
       aes(x = tai.3, y = fga.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  scale_y_log10() +
  labs(xlab("Total Aberration Index Score")) +
  labs(ylab("Fraction Genome Altered")) +
  ggtitle(label = "Total Aberration Index vs Fraction Genome Altered") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))

### tai vs cna
ggplot(tcga.df,
       aes(x = tai.3, y = cna.3,
           color = ifelse(`Sample Type` %in% c("Solid Tissue Normal", "Blood Derived Normal"), "Normal", "Tumor"))) +
  geom_point(alpha = 0.3, size = 2) +
  theme_minimal() +
  scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  #scale_y_continuous(trans = "log1p", breaks = c(0, 10, 100, 1000, 10000)) +
  labs(ylab("Number of Copy Number Aberrations")) +
  labs(xlab("Total Aberration Index Score")) +
  ggtitle(label = "Number of Break Points vs Total Aberration Index") +
  labs(color = NULL) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))
```

Strip Charts - Sasha

```{r}
library(ggpubr)
library(tidyverse)
library(ggsci)
library(devtools)

load("/data/project/lasseigne_lab/SashaThalluri/k99/cin-metrics/data/190318_cin-metrics-master_calcs_tcga.df.RData")

```


```{r}
##### Creating Strip Charts #####
## Data Cleaning
# Normal and Tumor Type Separation
tcga.df$`Sample Type` <- as.character(tcga.df$`Sample Type`)
tcga.df$`Sample Type` <- ifelse(tcga.df$`Sample Type` %in% c("Blood Derived Normal", "Solid Tissue Normal"), "Normal", tcga.df$`Sample Type`)
tcga.df$`Sample Type` <- ifelse(tcga.df$`Sample Type` %in% c("Primary Solid Tumor", "Metastatic", "Primary Blood Derived Cancer"), "Tumor", tcga.df$`Sample Type`)
# log10 Transformation
log10.tcga <- log10(tcga.df[, c(7:12)])
log10.tcga <- tcga.df[, -c(7:12)] %>% cbind(., log10.tcga)

## Strip Chart Plot
cin_metrics <- c("numBases.3", "numBreakPoints.3", "tai.3", "mod.tai.3", "fga.3", "cna.3")
pdf("/data/project/lasseigne_lab/SashaThalluri/k99/cin-metrics/results/210819_combinedstripplotscinmetrics.pdf", width = 8, height = 12)
ggstripchart(log10.tcga, x = "Project", y = cin_metrics, fill = "Sample Type", color = "Sample Type", palette = "simpsons", size = .05, xlab = "Cancer", ylab = "Value", position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), rotate = TRUE, alpha = .5, combine = TRUE, add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "Sample Type", color = "black")) 
dev.off()

```

-------------------------------------------------------------------
## CINmetrics with CINmetrics Package

```{r}
library(CINmetrics)
library(tidyverse)
library(ggpubr)
library(here)
library(ComplexHeatmap)
library(circlize)
library(reshape2)
```

## Creating CINmetrics Dataframe
```{r}
## Loading the data with all of the CNV data

all.cancer.df <- read.csv('~/Desktop/CINmetrics_Cancer_Analysis/data/processed/all_cancer_df.csv')

## The function takes the dataframe with all of the CNV data and calculates the CINmetrics. It is merged with the TCGA project name.

get_cinmetrics <- function(all.cancer.df){
# Calculating CINmetrics
modified.tai.cancer <- taiModified(all.cancer.df)
cinmetrics.cancer <- CINmetrics(all.cancer.df)
cinmetrics.cancer <- inner_join(cinmetrics.cancer, modified.tai.cancer, by = "sample_id")

# Adding Patient ID, Project, and Sample Type Columns to Dataframe
cinmetrics.cancer <- cinmetrics.cancer %>% separate(sample_id, "patient_id", 12, remove = FALSE)
all.cinmetrics.df <- inner_join(cinmetrics.cancer, all.cancer.df[,c(7,10,11)], by = c("sample_id" = "Sample")) %>% unique(.) %>% select("sample_id", "patient_id", "project", "sample_type", "tai", "modified_tai", "cna", "base_segments", "break_points", "fga")

## We store the output as a csv
all.cinmetrics.df <- write.csv(all.cinmetrics.df, file = here("data", "processed", "all_cinmetrics_df.csv"), row.names = FALSE)
return(all.cinmetrics.df)
}

all.cinmetrics.df <- get_cinmetrics(all.cancer.df)

```

## Creating CINmetrics Stripchart
```{r}
## This function will take the dataframe with all of the CINmetrics values and will plot a stripchart for all of the CINmetrics across all 33 cancers.

get_cinmetrics_stripchart <- function(all.cinmetrics.df){
# Grouping different sample types by normal and tumor samples
all.cinmetrics.df$sample_type <- ifelse(all.cinmetrics.df$sample_type %in% c("Blood Derived Normal", "Solid Tissue Normal", "Bone Marrow Normal", "Buccal Cell Normal"), "Normal", all.cinmetrics.df$sample_type)
all.cinmetrics.df$sample_type  <- ifelse(all.cinmetrics.df$sample_type  %in% c("Metastatic", "Primary Blood Derived Cancer", "Primary Tumor", "Recurrent Tumor", "Additional - New Primary", "Primary Blood Derived Cancer - Peripheral Blood"), "Tumor", all.cinmetrics.df$sample_type )

# Base Segments Plot
base.segments.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "base_segments", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(Base Segments)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "Base Segments",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"), 
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black")) 

# Number of Breakpoints Plot
break.points.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "break_points", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(Breakpoints)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "Breakpoints",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"),
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black"))
# Total Aberration Index Plot
tai.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "tai", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(TAI)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5, dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "TAI",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"),
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black")) 
# Fraction of Genome Altered Plot
fga.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "fga", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(FGA)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "FGA",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"),
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black")) 
# Copy Number Aberrations Plot
cna.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "cna", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(CNA)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "CNA",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"),
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black")) 
# Modified Total Aberration Index Plot
modified.tai.stripchart <- ggstripchart(all.cinmetrics.df,
                                      x = "project", y = "modified_tai", 
                                      fill = "sample_type", 
                                      color = "sample_type", 
                                      palette = "simpsons", 
                                      size = .05, 
                                      xlab = "Cancer", 
                                      ylab = "log10(Modified TAI)",
                                      yscale = "log10",
                                      format.scale = TRUE,
                                      position = position_jitterdodge(jitter.width = .7, jitter.height = .5 ,dodge.width = 3), 
                                      rotate = TRUE,
                                      alpha = .5, 
                                      combine = TRUE,
                                      title = "Modified TAI",
                                      font.main = c(11, "bold"),
                                      font.x = c(10, "bold"),
                                      font.y = c(10, "bold"),
                                      font.xtickslab = c(10, "bold"),
                                      font.ytickslab = c(7, "bold"),
                                      legend.title = "Sample Type",
                                      font.legend = c(10, "bold"),
                                      add = "mean_sd", add.params = list(size = .05, alpha = 1, group = "sample_type", color = "black")) 
# CINmetrics Plot
cinmetrics.stripchart <- ggarrange(base.segments.stripchart, 
                                   break.points.stripchart, 
                                   tai.stripchart, 
                                   fga.stripchart, 
                                   cna.stripchart,
                                   modified.tai.stripchart, 
                                   ncol = 3, nrow = 2, 
                                   legend = "right", 
                                   common.legend = TRUE)

return(cinmetrics.stripchart)
}

cinmetrics.stripchart <- get_cinmetrics_stripchart(all.cinmetrics.df)
cinmetrics.stripchart
```

## Creating CINmetrics Heatmaps
```{r}
## This function will take the all.cinmetrics.df, subset the tumor samples, and will plot a heatmap for all of the CINmetrics across all 33 cancers. For sample.type "normal" or "tumor" will be the input to produce the correct heatmap based on sample types. 

get_cinmetrics_heatmap <- function(all.cinmetrics.df, sample.type){

if(sample.type == "normal"){
# Subsetting all.cinmetrics.df by normal samples
normal.cinmetrics.df <- all.cinmetrics.df %>% filter(sample_type %in% c("Blood Derived Normal", "Solid Tissue Normal", "Bone Marrow Normal", "Buccal Cell Normal"))

# Performing Spearman's correlation across all CINmetrics values in normal samples
spearman.normal.cinmetrics <- normal.cinmetrics.df %>% select(tai, modified_tai, cna, base_segments, break_points, fga) %>% cor(., method = "spearman")
# Heatmap of Spearman's correlation
heatmap.colors <- colorRamp2(c(-1, 0, 1), c("#FED439FF", "#FFFFFF", "#709AE1FF"))
normal.cinmetrics.heatmap <- Heatmap(spearman.normal.cinmetrics,
                                    col = heatmap.colors,
                                    show_row_dend = FALSE,
                                    show_column_dend = FALSE,
                                    column_title = "Normal",
                                    column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                                    row_labels = c("TAI", "Modified TAI", "CNA", "Base Segments", "Breakpoints", "FGA"),
                                    row_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_labels = c("TAI", "Modified TAI", "CNA", "Base Segments", "Breakpoints", "FGA"),
                                    column_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_rot = 45,
                                    heatmap_legend_param = list(title = "Spearman's Rho", title_gp = gpar(fontsize = 10, fontface = "bold")))
return(normal.cinmetrics.heatmap)
}

if(sample.type == "tumor"){
# Subsetting all.cinmetrics.df by tumor samples
tumor.cinmetrics.df <- all.cinmetrics.df %>% filter(sample_type %in% c("Metastatic", "Primary Blood Derived Cancer", "Primary Tumor", "Recurrent Tumor", "Additional - New Primary", "Primary Blood Derived Cancer - Peripheral Blood"))
# Performing Spearman's correlation across all CINmetrics values in tumor samples
spearman.tumor.cinmetrics <- tumor.cinmetrics.df %>% select(tai, modified_tai, cna, base_segments, break_points, fga) %>% drop_na() %>% cor(., method = "spearman")
# Heatmap of Spearman's correlation
heatmap.colors <- colorRamp2(c(-1, 0, 1), c("#FED439FF", "#FFFFFF", "#709AE1FF"))
tumor.cinmetrics.heatmap <- Heatmap(spearman.tumor.cinmetrics,
                                    col = heatmap.colors,
                                    show_row_dend = FALSE,
                                    show_column_dend = FALSE,
                                    column_title = "Tumor",
                                    column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                                    row_labels = c("TAI", "Modified TAI", "CNA", "Base Segments", "Breakpoints", "FGA"),
                                    row_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_labels = c("TAI", "Modified TAI", "CNA", "Base Segments", "Breakpoints", "FGA"),
                                    column_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_rot = 45,
                                    heatmap_legend_param = list(title = "Spearman's Rho", title_gp = gpar(fontsize = 10, fontface = "bold")))
return(tumor.cinmetrics.heatmap)
}
}
normal.cinmetrics.heatmap <- get_cinmetrics_heatmap(all.cinmetrics.df, sample.type = "normal")
normal.cinmetrics.heatmap

tumor.cinmetrics.heatmap <- get_cinmetrics_heatmap(all.cinmetrics.df, sample.type = "tumor")
tumor.cinmetrics.heatmap
```

```{r}
## This function will subset the tumor samples from the all.cinmetrics.df and plot a heatmap for all of the CINmetrics separated by each of the 33 cancers. This function can only be used if there are 2 or more cancers being compared

## This function will calculate the Spearman's correlation for the CINmetrics and will produce a dataframe with the Spearman Rho values between each metric separated by cancer projects. This function can only be used if there are 2 or more cancers being compared


get_cinmetrics_cancer_heatmap <- function(all.cinmetrics.df, sample.type){
  if(sample.type == "tumor"){
    # Subsetting all.cinmetrics.df by tumor samples
    tumor.cinmetrics.df <- all.cinmetrics.df %>% filter(sample_type %in% c("Metastatic", "Primary Blood Derived Cancer", "Primary Tumor", "Recurrent Tumor", "Additional - New Primary", "Primary Blood Derived Cancer - Peripheral Blood"))
    
    # Creating df with Spearman Rho values from CINmetrics in each cancer
    spearman.variables <- names(tumor.cinmetrics.df)[c(5:10)]
    all.spearman.df <- tumor.cinmetrics.df %>% drop_na %>% split(.$project) %>% map(select, spearman.variables) %>% map(function(x) cor(x, method = "spearman")) %>% map(melt) %>% melt(.) %>% select(-"variable")
    names(all.spearman.df) <- c("cinmetric1", "cinmetric2", "spearman_rho", "project")
    
    # Filtering dataframe to have rows we will use for heatmap, inserting a column with comparison name to use in heatmap
    filtered.spearman.df <- filter(all.spearman.df, (cinmetric1 == "base_segments" & cinmetric2 %in% c("break_points", "cna", "fga", "modified_tai", "tai")) | (cinmetric1== "break_points" & cinmetric2 %in% c("cna", "modified_tai", "tai")) | (cinmetric1 == "cna" & cinmetric2 %in% c("modified_tai", "tai")) | (cinmetric1 == "fga" & cinmetric2 %in% c("break_points", "cna", "modified_tai", "tai")) | (cinmetric1 == "modified_tai" & cinmetric2 == "tai")) %>%
      mutate(comparison = ifelse(cinmetric1 %in%  "base_segments" & cinmetric2 %in% "break_points", "Base Segments vs Breakpoints", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "cna", "Base Segments vs CNA", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "fga", "Base Segments vs FGA", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "modified_tai", "Base Segments vs Modified TAI", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "tai", "Base Segments vs TAI", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "cna", "Breakpoints vs CNA", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "modified_tai", "Breakpoints vs Modified TAI", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "tai", "Breakpoints vs TAI", ifelse(cinmetric1 %in% "cna" & cinmetric2 %in% "modified_tai", "CNA vs Modified TAI", ifelse(cinmetric1 %in% "cna" & cinmetric2 %in% "tai", "CNA vs TAI", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "break_points", "FGA vs Breakpoints", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "cna", "FGA vs CNA", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "modified_tai", "FGA vs Modified TAI", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "tai", "FGA vs TAI", ifelse(cinmetric1 %in% "modified_tai" & cinmetric2 %in% "tai", "Modified TAI vs TAI", "NA"))))))))))))))))
    
    # Transforming dataframe to use for heatmap
    transformed.spearman.df <- filtered.spearman.df %>% select(project, comparison, spearman_rho) %>% pivot_wider(names_from = comparison, values_from = spearman_rho)
    transformed.spearman.df$project <- str_remove(transformed.spearman.df$project, "TCGA-") 
    transformed.spearman.df <- column_to_rownames(transformed.spearman.df, var = "project")
    
    # Creating Heatmap
    heatmap.colors <- colorRamp2(c(-1, 0, 1), c("#FED439FF", "#FFFFFF", "#709AE1FF"))
    tumor.cancer.heatmap <- Heatmap(transformed.spearman.df,
                                    rect_gp = gpar(col = "white", lwd = .5),
                                    col = heatmap.colors,
                                    show_column_dend = TRUE,
                                    show_row_dend = FALSE,
                                    column_title = "Tumor",
                                    column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                                    row_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_rot = 45,
                                    heatmap_legend_param = list(title = "Spearman's Rho", title_gp = gpar(fontsize = 10, fontface = "bold")))
    return(tumor.cancer.heatmap)
  }
    if(sample.type == "normal"){
    # Subsetting all.cinmetrics.df by normal samples
    normal.cinmetrics.df <- all.cinmetrics.df %>% filter(sample_type %in% c("Blood Derived Normal", "Solid Tissue Normal", "Bone Marrow Normal", "Buccal Cell Normal"))
    
    # Creating df with Spearman Rho values from CINmetrics in each cancer
    spearman.variables <- names(normal.cinmetrics.df)[c(5:10)]
    all.spearman.df <- normal.cinmetrics.df %>% drop_na %>% split(.$project) %>% map(select, spearman.variables) %>% map(function(x) cor(x, method = "spearman")) %>% map(melt) %>% melt(.) %>% select(-"variable")
    names(all.spearman.df) <- c("cinmetric1", "cinmetric2", "spearman_rho", "project")
    
    # Filtering dataframe to have rows we will use for heatmap, inserting a column with comparison name to use in heatmap
    filtered.spearman.df <- filter(all.spearman.df, (cinmetric1 == "base_segments" & cinmetric2 %in% c("break_points", "cna", "fga", "modified_tai", "tai")) | (cinmetric1== "break_points" & cinmetric2 %in% c("cna", "modified_tai", "tai")) | (cinmetric1 == "cna" & cinmetric2 %in% c("modified_tai", "tai")) | (cinmetric1 == "fga" & cinmetric2 %in% c("break_points", "cna", "modified_tai", "tai")) | (cinmetric1 == "modified_tai" & cinmetric2 == "tai")) %>%
      mutate(comparison = ifelse(cinmetric1 %in%  "base_segments" & cinmetric2 %in% "break_points", "Base Segments vs Breakpoints", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "cna", "Base Segments vs CNA", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "fga", "Base Segments vs FGA", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "modified_tai", "Base Segments vs Modified TAI", ifelse(cinmetric1 %in% "base_segments" & cinmetric2 %in% "tai", "Base Segments vs TAI", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "cna", "Breakpoints vs CNA", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "modified_tai", "Breakpoints vs Modified TAI", ifelse(cinmetric1 %in% "break_points" & cinmetric2 %in% "tai", "Breakpoints vs TAI", ifelse(cinmetric1 %in% "cna" & cinmetric2 %in% "modified_tai", "CNA vs Modified TAI", ifelse(cinmetric1 %in% "cna" & cinmetric2 %in% "tai", "CNA vs TAI", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "break_points", "FGA vs Breakpoints", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "cna", "FGA vs CNA", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "modified_tai", "FGA vs Modified TAI", ifelse(cinmetric1 %in% "fga" & cinmetric2 %in% "tai", "FGA vs TAI", ifelse(cinmetric1 %in% "modified_tai" & cinmetric2 %in% "tai", "Modified TAI vs TAI", "NA"))))))))))))))))
    
    # Transforming dataframe to use for heatmap
    transformed.spearman.df <- filtered.spearman.df %>% select(project, comparison, spearman_rho) %>% pivot_wider(names_from = comparison, values_from = spearman_rho)
    transformed.spearman.df$project <- str_remove(transformed.spearman.df$project, "TCGA-") 
    transformed.spearman.df <- column_to_rownames(transformed.spearman.df, var = "project")
    
    # Creating Heatmap
    heatmap.colors <- colorRamp2(c(-1, 0, 1), c("#FED439FF", "#FFFFFF", "#709AE1FF"))
    normal.cancer.heatmap <- Heatmap(transformed.spearman.df,
                                    rect_gp = gpar(col = "white", lwd = .5),
                                    col = heatmap.colors,
                                    show_column_dend = TRUE,
                                    show_row_dend = FALSE,
                                    column_title = "Normal",
                                    column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                                    row_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_gp = gpar(fontsize = 10, fontface = "bold"),
                                    column_names_rot = 45,
                                    heatmap_legend_param = list(title = "Spearman's Rho", title_gp = gpar(fontsize = 10, fontface = "bold")))
    return(normal.cancer.heatmap)
  } 
  else{
    stop("Incorrect input for cancer.project. Make sure there are 2 or more cancer projects")
  }
}

normal.cancer.heatmap <- get_cinmetrics_cancer_heatmap(all.cinmetrics.df, sample.type = "normal")
normal.cancer.heatmap

tumor.cancer.heatmap <- get_cinmetrics_cancer_heatmap(all.cinmetrics.df, sample.type = "tumor")
tumor.cancer.heatmap


```

